project_id = "vgffjuvaedmxoxvzovoq"

[functions.daily-rolling-schedule]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.generate-avatar]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.generate-video-sora]
verify_jwt = false

[functions.meta-oauth]
verify_jwt = false

[functions.scrape-project-url]
verify_jwt = false

[functions.suggest-content]
verify_jwt = false

[functions.generate-monthly-schedule]
verify_jwt = false

[functions.generate-script-nanobanana]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
