import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, ArrowUp, Check, Loader2, Sparkles, Quote } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SEOHead } from "@/components/seo/SEOHead";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

const SAMPLE_THUMBS = [
  "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400",
  "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400",
  "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
  "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
  "https://images.unsplash.com/photo-1581338834647-b0fb40704e21?w=400",
  "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
  "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400",
  "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=400",
  "https://images.unsplash.com/photo-1518049362265-d5b2a6b00b37?w=400",
  "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400",
];

const ANIMATED_HEADLINES = [
  "Product shots in seconds",
  "Studio quality, zero studio",
  "Mobile-ready ads from a link",
  "Turn any product page into ads",
];

export default function MobileAdsPage() {
  const navigate = useNavigate();
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ images: string[]; productTitle?: string } | null>(null);
  const [headlineIdx, setHeadlineIdx] = useState(0);

  useEffect(() => {
    const t = setInterval(() => setHeadlineIdx((i) => (i + 1) % ANIMATED_HEADLINES.length), 2800);
    return () => clearInterval(t);
  }, []);

  const handleGenerate = async () => {
    const trimmed = url.trim();
    if (!trimmed) return toast.error("Paste your product URL first");
    if (!/^https?:\/\//i.test(trimmed)) return toast.error("URL must start with http:// or https://");
    setLoading(true);
    setResult(null);
    try {
      const { data, error } = await supabase.functions.invoke("mobileads-generate", {
        body: { url: trimmed },
      });
      if (error) throw error;
      if (data?.alreadyUsed && data?.images?.length) {
        setResult({ images: data.images, productTitle: data.productTitle });
        toast.info("Here is your previous trial. Sign up for unlimited generations.");
      } else if (data?.alreadyUsed) {
        toast.error(data.error || "Free trial already used. Sign up to continue.");
      } else if (data?.images?.length) {
        setResult({ images: data.images, productTitle: data.productTitle });
        toast.success("Your samples are ready");
      } else {
        toast.error(data?.error || "Failed to generate. Try a different URL.");
      }
    } catch (e: any) {
      console.error(e);
      toast.error(e?.message || "Generation failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#FAFAF9] text-zinc-900">
      <SEOHead
        title="MobileAds — AI product shots in seconds | ClipMotion"
        description="Paste your product URL and get 4 stunning mobile-ready ad visuals generated by AI. Free trial, no signup required."
        canonical="https://clipmotion.ai/mobileads"
        keywords="ai product shots, mobile ads, instagram ads ai, product photography ai, ai ad creator"
      />

      {/* Top brand pill */}
      <header className="sticky top-0 z-30 backdrop-blur bg-white/70 border-b border-black/5">
        <div className="container mx-auto px-4 py-3 flex items-center justify-between">
          <Link to="/" className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white shadow-sm border">
            <div className="h-6 w-6 rounded-md bg-gradient-to-br from-violet-600 to-fuchsia-500 grid place-items-center text-white text-xs font-black">C</div>
            <span className="font-semibold text-sm">ClipMotion</span>
          </Link>
          <Link to="/auth">
            <Button size="sm" className="rounded-full bg-zinc-900 hover:bg-zinc-800 text-white">Get started</Button>
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-4 max-w-md md:max-w-xl pb-20">
        {!result && (
          <>
            {/* Hero */}
            <section className="pt-8 md:pt-12 text-center">
              <h1 className="font-display text-4xl md:text-5xl font-black tracking-tight leading-[1.05] mb-4">
                Product shots
                <br />
                <span className="inline-block min-h-[1.2em]">
                  <AnimatePresence mode="wait">
                    <motion.span
                      key={headlineIdx}
                      initial={{ y: 14, opacity: 0 }}
                      animate={{ y: 0, opacity: 1 }}
                      exit={{ y: -14, opacity: 0 }}
                      transition={{ duration: 0.4 }}
                      className="bg-gradient-to-r from-violet-600 to-fuchsia-500 bg-clip-text text-transparent"
                    >
                      {ANIMATED_HEADLINES[headlineIdx]}
                    </motion.span>
                  </AnimatePresence>
                </span>
              </h1>

              {/* Stacked sample preview */}
              <motion.div
                initial={{ opacity: 0, y: 20, rotate: -3 }}
                animate={{ opacity: 1, y: 0, rotate: -3 }}
                transition={{ duration: 0.6 }}
                className="relative w-44 h-44 mx-auto my-6"
              >
                <div className="absolute inset-0 rounded-2xl bg-zinc-200 rotate-6 shadow-lg" />
                <div className="absolute inset-0 rounded-2xl bg-zinc-300 rotate-3 shadow-lg" />
                <img
                  src={SAMPLE_THUMBS[0]}
                  alt="Sample AI product shot"
                  className="absolute inset-0 w-full h-full object-cover rounded-2xl shadow-xl"
                />
              </motion.div>

              <p className="text-sm text-zinc-600 mb-4">
                Paste your online store URL to create AI product shots
              </p>

              {/* URL input */}
              <div className="relative">
                <input
                  type="url"
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  placeholder="Enter online store URL"
                  className="w-full rounded-full border border-zinc-200 bg-white pl-5 pr-14 py-4 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-violet-500/30"
                  disabled={loading}
                  onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
                />
                <button
                  onClick={handleGenerate}
                  disabled={loading}
                  className="absolute right-1.5 top-1/2 -translate-y-1/2 h-11 w-11 rounded-full bg-zinc-900 text-white grid place-items-center hover:bg-zinc-700 disabled:opacity-50 transition"
                  aria-label="Generate"
                >
                  {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <ArrowUp className="h-4 w-4" />}
                </button>
              </div>
            </section>

            {/* Works with most products */}
            <section className="pt-12">
              <h2 className="text-center font-bold text-xl mb-6">Works with most products</h2>
              <div className="grid grid-cols-2 gap-3">
                {SAMPLE_THUMBS.slice(0, 10).map((src, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, scale: 0.95 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.05 }}
                    className="aspect-[3/4] rounded-xl overflow-hidden bg-zinc-100"
                  >
                    <img src={src} alt={`Sample ${i + 1}`} className="w-full h-full object-cover" />
                  </motion.div>
                ))}
              </div>
            </section>

            {/* Bottom CTA */}
            <section className="pt-16 text-center">
              <h2 className="font-display text-3xl font-black mb-3">Product photos in minutes</h2>
              <p className="text-sm text-zinc-600 mb-6">
                Create studio-quality product imagery without a studio-sized budget
              </p>
              <ul className="text-left max-w-xs mx-auto space-y-2 mb-8 text-sm">
                {[
                  "Import all your products",
                  "Choose from professional presets",
                  "Put products on AI models",
                  "Generate high-quality images and videos",
                ].map((f) => (
                  <li key={f} className="flex items-start gap-2">
                    <Check className="h-4 w-4 text-violet-600 mt-0.5 shrink-0" />
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
              <Button
                size="lg"
                className="rounded-full bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white hover:opacity-90 px-8"
                onClick={() => navigate("/auth?plan=pro")}
              >
                <ArrowRight className="h-4 w-4 mr-2" />
                Get started free
              </Button>
            </section>
          </>
        )}

        {/* Result state */}
        {result && (
          <section className="pt-10 text-center">
            <motion.h1
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="font-display text-4xl font-black mb-2"
            >
              Nice work!
            </motion.h1>
            <p className="text-zinc-600 mb-6">Your first samples are ready</p>

            <div className="grid grid-cols-2 gap-3 mb-8">
              {result.images.map((src, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.08 }}
                  className="aspect-[3/4] rounded-xl overflow-hidden bg-zinc-100 shadow-sm"
                >
                  <img src={src} alt={`Generated ${i + 1}`} className="w-full h-full object-cover" />
                </motion.div>
              ))}
            </div>

            <h2 className="font-display text-2xl font-bold mb-2">
              Try more <span className="inline-block animate-pulse">✨</span> products and keep creating
            </h2>
            <p className="text-sm text-zinc-600 mb-6">
              Sign up to import more products, use professional AI presets and create stunning visuals.
            </p>
            <ul className="text-left max-w-xs mx-auto space-y-2 mb-8 text-sm">
              {[
                "Import all your products",
                "Choose from professional presets",
                "Put products on AI models",
                "Generate high-quality images and videos",
              ].map((f) => (
                <li key={f} className="flex items-start gap-2">
                  <Check className="h-4 w-4 text-violet-600 mt-0.5 shrink-0" />
                  <span>{f}</span>
                </li>
              ))}
            </ul>

            <div className="space-y-3">
              <Button
                size="lg"
                className="w-full rounded-full bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white hover:opacity-90"
                onClick={() => navigate("/auth?plan=starter&from=mobileads")}
              >
                <ArrowRight className="h-4 w-4 mr-2" />
                Sign up for free
              </Button>
              <Button
                size="lg"
                variant="outline"
                className="w-full rounded-full"
                onClick={() => {
                  setResult(null);
                  setUrl("");
                }}
              >
                Try again
              </Button>
            </div>

            {/* Testimonial */}
            <div className="mt-12 border-t pt-8">
              <Quote className="h-5 w-5 mx-auto text-zinc-400 mb-2" />
              <p className="italic font-semibold text-zinc-800 max-w-xs mx-auto">
                ClipMotion was my last ditch attempt at making AI work.<br />
                This is just fantastic.
              </p>
              <div className="mt-3 text-sm text-zinc-500">– Emily</div>
              <div className="mt-2 inline-block px-3 py-1 rounded-full border text-xs text-zinc-600">
                Saved $5,000 on a shoot
              </div>
            </div>
          </section>
        )}
      </main>

      <footer className="border-t border-black/5 py-6 text-center text-xs text-zinc-500">
        <Sparkles className="h-3 w-3 inline mr-1" />
        Powered by ClipMotion AI · <Link to="/privacy-policy" className="underline">Privacy</Link>
      </footer>
    </div>
  );
}
