/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AiVideoGeneratorRouteImport } from './routes/ai-video-generator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChoosePlanRouteImport } from './routes/choose-plan'
import { Route as ClipMotionFaqRouteImport } from './routes/clip-motion-faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as MotionDesignAiRouteImport } from './routes/motion-design-ai'
import { Route as NanobananavideoRouteImport } from './routes/nanobananavideo'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as ShellCalendarRouteImport } from './routes/_shell.calendar'
import { Route as ShellCampaignsRouteImport } from './routes/_shell.campaigns'
import { Route as ShellCreateRouteImport } from './routes/_shell.create'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellImageToVideoRouteImport } from './routes/_shell.image-to-video'
import { Route as ShellImagesRouteImport } from './routes/_shell.images'
import { Route as ShellImagesLegacyRouteImport } from './routes/_shell.images-legacy'
import { Route as ShellIntegrationsRouteImport } from './routes/_shell.integrations'
import { Route as ShellPostsRouteImport } from './routes/_shell.posts'
import { Route as ShellProductShotsRouteImport } from './routes/_shell.product-shots'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSmartImageRouteImport } from './routes/_shell.smart-image'
import { Route as ShellVideosRouteImport } from './routes/_shell.videos'
import { Route as ShellVideosLegacyRouteImport } from './routes/_shell.videos-legacy'
import { Route as ShellVoiceoverRouteImport } from './routes/_shell.voiceover'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogAiVideoAdsGeneratorRouteImport } from './routes/blog.ai-video-ads-generator'
import { Route as BlogAiVideoForEcommerceRouteImport } from './routes/blog.ai-video-for-ecommerce'
import { Route as BlogBestAiVideoGenerators2026RouteImport } from './routes/blog.best-ai-video-generators-2026'
import { Route as BlogClipMotionRouteImport } from './routes/blog.clip-motion'
import { Route as BlogInstagramReelsAiGeneratorRouteImport } from './routes/blog.instagram-reels-ai-generator'
import { Route as BlogKlingImageAiRouteImport } from './routes/blog.kling-image-ai'
import { Route as BlogKlingVideoAiRouteImport } from './routes/blog.kling-video-ai'
import { Route as BlogNanoBananaProRouteImport } from './routes/blog.nano-banana-pro'
import { Route as BlogNanoBananaVideoGuideRouteImport } from './routes/blog.nano-banana-video-guide'
import { Route as BlogSoraAiVideoGeneratorRouteImport } from './routes/blog.sora-ai-video-generator'
import { Route as BlogTextToVideoAiCompleteGuideRouteImport } from './routes/blog.text-to-video-ai-complete-guide'
import { Route as BlogTiktokVideosWithAiRouteImport } from './routes/blog.tiktok-videos-with-ai'
import { Route as ShellHistoryIndexRouteImport } from './routes/_shell.history.index'
import { Route as ShellHistoryPostsRouteImport } from './routes/_shell.history.posts'
import { Route as ShellProjectsIndexRouteImport } from './routes/_shell.projects.index'
import { Route as ShellProjectsIdRouteImport } from './routes/_shell.projects.$id'
import { Route as ShellProjectsNewRouteImport } from './routes/_shell.projects.new'
import { Route as ApiTiktokCallbackRouteImport } from './routes/api.tiktok.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVideoGeneratorRoute = AiVideoGeneratorRouteImport.update({
  id: '/ai-video-generator',
  path: '/ai-video-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoosePlanRoute = ChoosePlanRouteImport.update({
  id: '/choose-plan',
  path: '/choose-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipMotionFaqRoute = ClipMotionFaqRouteImport.update({
  id: '/clip-motion-faq',
  path: '/clip-motion-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionDesignAiRoute = MotionDesignAiRouteImport.update({
  id: '/motion-design-ai',
  path: '/motion-design-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const NanobananavideoRoute = NanobananavideoRouteImport.update({
  id: '/nanobananavideo',
  path: '/nanobananavideo',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCalendarRoute = ShellCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCampaignsRoute = ShellCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCreateRoute = ShellCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellImageToVideoRoute = ShellImageToVideoRouteImport.update({
  id: '/image-to-video',
  path: '/image-to-video',
  getParentRoute: () => ShellRoute,
} as any)
const ShellImagesRoute = ShellImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => ShellRoute,
} as any)
const ShellImagesLegacyRoute = ShellImagesLegacyRouteImport.update({
  id: '/images-legacy',
  path: '/images-legacy',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegrationsRoute = ShellIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPostsRoute = ShellPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductShotsRoute = ShellProductShotsRouteImport.update({
  id: '/product-shots',
  path: '/product-shots',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSmartImageRoute = ShellSmartImageRouteImport.update({
  id: '/smart-image',
  path: '/smart-image',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVideosRoute = ShellVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVideosLegacyRoute = ShellVideosLegacyRouteImport.update({
  id: '/videos-legacy',
  path: '/videos-legacy',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVoiceoverRoute = ShellVoiceoverRouteImport.update({
  id: '/voiceover',
  path: '/voiceover',
  getParentRoute: () => ShellRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAiVideoAdsGeneratorRoute = BlogAiVideoAdsGeneratorRouteImport.update({
  id: '/blog/ai-video-ads-generator',
  path: '/blog/ai-video-ads-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAiVideoForEcommerceRoute = BlogAiVideoForEcommerceRouteImport.update({
  id: '/blog/ai-video-for-ecommerce',
  path: '/blog/ai-video-for-ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBestAiVideoGenerators2026Route =
  BlogBestAiVideoGenerators2026RouteImport.update({
    id: '/blog/best-ai-video-generators-2026',
    path: '/blog/best-ai-video-generators-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogClipMotionRoute = BlogClipMotionRouteImport.update({
  id: '/blog/clip-motion',
  path: '/blog/clip-motion',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogInstagramReelsAiGeneratorRoute =
  BlogInstagramReelsAiGeneratorRouteImport.update({
    id: '/blog/instagram-reels-ai-generator',
    path: '/blog/instagram-reels-ai-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogKlingImageAiRoute = BlogKlingImageAiRouteImport.update({
  id: '/blog/kling-image-ai',
  path: '/blog/kling-image-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogKlingVideoAiRoute = BlogKlingVideoAiRouteImport.update({
  id: '/blog/kling-video-ai',
  path: '/blog/kling-video-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNanoBananaProRoute = BlogNanoBananaProRouteImport.update({
  id: '/blog/nano-banana-pro',
  path: '/blog/nano-banana-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNanoBananaVideoGuideRoute =
  BlogNanoBananaVideoGuideRouteImport.update({
    id: '/blog/nano-banana-video-guide',
    path: '/blog/nano-banana-video-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSoraAiVideoGeneratorRoute =
  BlogSoraAiVideoGeneratorRouteImport.update({
    id: '/blog/sora-ai-video-generator',
    path: '/blog/sora-ai-video-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTextToVideoAiCompleteGuideRoute =
  BlogTextToVideoAiCompleteGuideRouteImport.update({
    id: '/blog/text-to-video-ai-complete-guide',
    path: '/blog/text-to-video-ai-complete-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTiktokVideosWithAiRoute = BlogTiktokVideosWithAiRouteImport.update({
  id: '/blog/tiktok-videos-with-ai',
  path: '/blog/tiktok-videos-with-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellHistoryIndexRoute = ShellHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHistoryPostsRoute = ShellHistoryPostsRouteImport.update({
  id: '/history/posts',
  path: '/history/posts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsIndexRoute = ShellProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsIdRoute = ShellProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsNewRoute = ShellProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => ShellRoute,
} as any)
const ApiTiktokCallbackRoute = ApiTiktokCallbackRouteImport.update({
  id: '/api/tiktok/callback',
  path: '/api/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai-video-generator': typeof AiVideoGeneratorRoute
  '/auth': typeof AuthRoute
  '/choose-plan': typeof ChoosePlanRoute
  '/clip-motion-faq': typeof ClipMotionFaqRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/motion-design-ai': typeof MotionDesignAiRoute
  '/nanobananavideo': typeof NanobananavideoRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/calendar': typeof ShellCalendarRoute
  '/campaigns': typeof ShellCampaignsRoute
  '/create': typeof ShellCreateRoute
  '/dashboard': typeof ShellDashboardRoute
  '/image-to-video': typeof ShellImageToVideoRoute
  '/images': typeof ShellImagesRoute
  '/images-legacy': typeof ShellImagesLegacyRoute
  '/integrations': typeof ShellIntegrationsRoute
  '/posts': typeof ShellPostsRoute
  '/product-shots': typeof ShellProductShotsRoute
  '/settings': typeof ShellSettingsRoute
  '/smart-image': typeof ShellSmartImageRoute
  '/videos': typeof ShellVideosRoute
  '/videos-legacy': typeof ShellVideosLegacyRoute
  '/voiceover': typeof ShellVoiceoverRoute
  '/blog/ai-video-ads-generator': typeof BlogAiVideoAdsGeneratorRoute
  '/blog/ai-video-for-ecommerce': typeof BlogAiVideoForEcommerceRoute
  '/blog/best-ai-video-generators-2026': typeof BlogBestAiVideoGenerators2026Route
  '/blog/clip-motion': typeof BlogClipMotionRoute
  '/blog/instagram-reels-ai-generator': typeof BlogInstagramReelsAiGeneratorRoute
  '/blog/kling-image-ai': typeof BlogKlingImageAiRoute
  '/blog/kling-video-ai': typeof BlogKlingVideoAiRoute
  '/blog/nano-banana-pro': typeof BlogNanoBananaProRoute
  '/blog/nano-banana-video-guide': typeof BlogNanoBananaVideoGuideRoute
  '/blog/sora-ai-video-generator': typeof BlogSoraAiVideoGeneratorRoute
  '/blog/text-to-video-ai-complete-guide': typeof BlogTextToVideoAiCompleteGuideRoute
  '/blog/tiktok-videos-with-ai': typeof BlogTiktokVideosWithAiRoute
  '/blog/': typeof BlogIndexRoute
  '/history/posts': typeof ShellHistoryPostsRoute
  '/projects/$id': typeof ShellProjectsIdRoute
  '/projects/new': typeof ShellProjectsNewRoute
  '/api/tiktok/callback': typeof ApiTiktokCallbackRoute
  '/history/': typeof ShellHistoryIndexRoute
  '/projects/': typeof ShellProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai-video-generator': typeof AiVideoGeneratorRoute
  '/auth': typeof AuthRoute
  '/choose-plan': typeof ChoosePlanRoute
  '/clip-motion-faq': typeof ClipMotionFaqRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/motion-design-ai': typeof MotionDesignAiRoute
  '/nanobananavideo': typeof NanobananavideoRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/calendar': typeof ShellCalendarRoute
  '/campaigns': typeof ShellCampaignsRoute
  '/create': typeof ShellCreateRoute
  '/dashboard': typeof ShellDashboardRoute
  '/image-to-video': typeof ShellImageToVideoRoute
  '/images': typeof ShellImagesRoute
  '/images-legacy': typeof ShellImagesLegacyRoute
  '/integrations': typeof ShellIntegrationsRoute
  '/posts': typeof ShellPostsRoute
  '/product-shots': typeof ShellProductShotsRoute
  '/settings': typeof ShellSettingsRoute
  '/smart-image': typeof ShellSmartImageRoute
  '/videos': typeof ShellVideosRoute
  '/videos-legacy': typeof ShellVideosLegacyRoute
  '/voiceover': typeof ShellVoiceoverRoute
  '/blog/ai-video-ads-generator': typeof BlogAiVideoAdsGeneratorRoute
  '/blog/ai-video-for-ecommerce': typeof BlogAiVideoForEcommerceRoute
  '/blog/best-ai-video-generators-2026': typeof BlogBestAiVideoGenerators2026Route
  '/blog/clip-motion': typeof BlogClipMotionRoute
  '/blog/instagram-reels-ai-generator': typeof BlogInstagramReelsAiGeneratorRoute
  '/blog/kling-image-ai': typeof BlogKlingImageAiRoute
  '/blog/kling-video-ai': typeof BlogKlingVideoAiRoute
  '/blog/nano-banana-pro': typeof BlogNanoBananaProRoute
  '/blog/nano-banana-video-guide': typeof BlogNanoBananaVideoGuideRoute
  '/blog/sora-ai-video-generator': typeof BlogSoraAiVideoGeneratorRoute
  '/blog/text-to-video-ai-complete-guide': typeof BlogTextToVideoAiCompleteGuideRoute
  '/blog/tiktok-videos-with-ai': typeof BlogTiktokVideosWithAiRoute
  '/blog': typeof BlogIndexRoute
  '/history/posts': typeof ShellHistoryPostsRoute
  '/projects/$id': typeof ShellProjectsIdRoute
  '/projects/new': typeof ShellProjectsNewRoute
  '/api/tiktok/callback': typeof ApiTiktokCallbackRoute
  '/history': typeof ShellHistoryIndexRoute
  '/projects': typeof ShellProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_shell': typeof ShellRouteWithChildren
  '/ai-video-generator': typeof AiVideoGeneratorRoute
  '/auth': typeof AuthRoute
  '/choose-plan': typeof ChoosePlanRoute
  '/clip-motion-faq': typeof ClipMotionFaqRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/motion-design-ai': typeof MotionDesignAiRoute
  '/nanobananavideo': typeof NanobananavideoRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/_shell/calendar': typeof ShellCalendarRoute
  '/_shell/campaigns': typeof ShellCampaignsRoute
  '/_shell/create': typeof ShellCreateRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/image-to-video': typeof ShellImageToVideoRoute
  '/_shell/images': typeof ShellImagesRoute
  '/_shell/images-legacy': typeof ShellImagesLegacyRoute
  '/_shell/integrations': typeof ShellIntegrationsRoute
  '/_shell/posts': typeof ShellPostsRoute
  '/_shell/product-shots': typeof ShellProductShotsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/smart-image': typeof ShellSmartImageRoute
  '/_shell/videos': typeof ShellVideosRoute
  '/_shell/videos-legacy': typeof ShellVideosLegacyRoute
  '/_shell/voiceover': typeof ShellVoiceoverRoute
  '/blog/ai-video-ads-generator': typeof BlogAiVideoAdsGeneratorRoute
  '/blog/ai-video-for-ecommerce': typeof BlogAiVideoForEcommerceRoute
  '/blog/best-ai-video-generators-2026': typeof BlogBestAiVideoGenerators2026Route
  '/blog/clip-motion': typeof BlogClipMotionRoute
  '/blog/instagram-reels-ai-generator': typeof BlogInstagramReelsAiGeneratorRoute
  '/blog/kling-image-ai': typeof BlogKlingImageAiRoute
  '/blog/kling-video-ai': typeof BlogKlingVideoAiRoute
  '/blog/nano-banana-pro': typeof BlogNanoBananaProRoute
  '/blog/nano-banana-video-guide': typeof BlogNanoBananaVideoGuideRoute
  '/blog/sora-ai-video-generator': typeof BlogSoraAiVideoGeneratorRoute
  '/blog/text-to-video-ai-complete-guide': typeof BlogTextToVideoAiCompleteGuideRoute
  '/blog/tiktok-videos-with-ai': typeof BlogTiktokVideosWithAiRoute
  '/blog/': typeof BlogIndexRoute
  '/_shell/history/posts': typeof ShellHistoryPostsRoute
  '/_shell/projects/$id': typeof ShellProjectsIdRoute
  '/_shell/projects/new': typeof ShellProjectsNewRoute
  '/api/tiktok/callback': typeof ApiTiktokCallbackRoute
  '/_shell/history/': typeof ShellHistoryIndexRoute
  '/_shell/projects/': typeof ShellProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ai-video-generator'
    | '/auth'
    | '/choose-plan'
    | '/clip-motion-faq'
    | '/contact'
    | '/faq'
    | '/features'
    | '/motion-design-ai'
    | '/nanobananavideo'
    | '/pricing'
    | '/privacy-policy'
    | '/terms'
    | '/use-cases'
    | '/calendar'
    | '/campaigns'
    | '/create'
    | '/dashboard'
    | '/image-to-video'
    | '/images'
    | '/images-legacy'
    | '/integrations'
    | '/posts'
    | '/product-shots'
    | '/settings'
    | '/smart-image'
    | '/videos'
    | '/videos-legacy'
    | '/voiceover'
    | '/blog/ai-video-ads-generator'
    | '/blog/ai-video-for-ecommerce'
    | '/blog/best-ai-video-generators-2026'
    | '/blog/clip-motion'
    | '/blog/instagram-reels-ai-generator'
    | '/blog/kling-image-ai'
    | '/blog/kling-video-ai'
    | '/blog/nano-banana-pro'
    | '/blog/nano-banana-video-guide'
    | '/blog/sora-ai-video-generator'
    | '/blog/text-to-video-ai-complete-guide'
    | '/blog/tiktok-videos-with-ai'
    | '/blog/'
    | '/history/posts'
    | '/projects/$id'
    | '/projects/new'
    | '/api/tiktok/callback'
    | '/history/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ai-video-generator'
    | '/auth'
    | '/choose-plan'
    | '/clip-motion-faq'
    | '/contact'
    | '/faq'
    | '/features'
    | '/motion-design-ai'
    | '/nanobananavideo'
    | '/pricing'
    | '/privacy-policy'
    | '/terms'
    | '/use-cases'
    | '/calendar'
    | '/campaigns'
    | '/create'
    | '/dashboard'
    | '/image-to-video'
    | '/images'
    | '/images-legacy'
    | '/integrations'
    | '/posts'
    | '/product-shots'
    | '/settings'
    | '/smart-image'
    | '/videos'
    | '/videos-legacy'
    | '/voiceover'
    | '/blog/ai-video-ads-generator'
    | '/blog/ai-video-for-ecommerce'
    | '/blog/best-ai-video-generators-2026'
    | '/blog/clip-motion'
    | '/blog/instagram-reels-ai-generator'
    | '/blog/kling-image-ai'
    | '/blog/kling-video-ai'
    | '/blog/nano-banana-pro'
    | '/blog/nano-banana-video-guide'
    | '/blog/sora-ai-video-generator'
    | '/blog/text-to-video-ai-complete-guide'
    | '/blog/tiktok-videos-with-ai'
    | '/blog'
    | '/history/posts'
    | '/projects/$id'
    | '/projects/new'
    | '/api/tiktok/callback'
    | '/history'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_shell'
    | '/ai-video-generator'
    | '/auth'
    | '/choose-plan'
    | '/clip-motion-faq'
    | '/contact'
    | '/faq'
    | '/features'
    | '/motion-design-ai'
    | '/nanobananavideo'
    | '/pricing'
    | '/privacy-policy'
    | '/terms'
    | '/use-cases'
    | '/_shell/calendar'
    | '/_shell/campaigns'
    | '/_shell/create'
    | '/_shell/dashboard'
    | '/_shell/image-to-video'
    | '/_shell/images'
    | '/_shell/images-legacy'
    | '/_shell/integrations'
    | '/_shell/posts'
    | '/_shell/product-shots'
    | '/_shell/settings'
    | '/_shell/smart-image'
    | '/_shell/videos'
    | '/_shell/videos-legacy'
    | '/_shell/voiceover'
    | '/blog/ai-video-ads-generator'
    | '/blog/ai-video-for-ecommerce'
    | '/blog/best-ai-video-generators-2026'
    | '/blog/clip-motion'
    | '/blog/instagram-reels-ai-generator'
    | '/blog/kling-image-ai'
    | '/blog/kling-video-ai'
    | '/blog/nano-banana-pro'
    | '/blog/nano-banana-video-guide'
    | '/blog/sora-ai-video-generator'
    | '/blog/text-to-video-ai-complete-guide'
    | '/blog/tiktok-videos-with-ai'
    | '/blog/'
    | '/_shell/history/posts'
    | '/_shell/projects/$id'
    | '/_shell/projects/new'
    | '/api/tiktok/callback'
    | '/_shell/history/'
    | '/_shell/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ShellRoute: typeof ShellRouteWithChildren
  AiVideoGeneratorRoute: typeof AiVideoGeneratorRoute
  AuthRoute: typeof AuthRoute
  ChoosePlanRoute: typeof ChoosePlanRoute
  ClipMotionFaqRoute: typeof ClipMotionFaqRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  MotionDesignAiRoute: typeof MotionDesignAiRoute
  NanobananavideoRoute: typeof NanobananavideoRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  UseCasesRoute: typeof UseCasesRoute
  BlogAiVideoAdsGeneratorRoute: typeof BlogAiVideoAdsGeneratorRoute
  BlogAiVideoForEcommerceRoute: typeof BlogAiVideoForEcommerceRoute
  BlogBestAiVideoGenerators2026Route: typeof BlogBestAiVideoGenerators2026Route
  BlogClipMotionRoute: typeof BlogClipMotionRoute
  BlogInstagramReelsAiGeneratorRoute: typeof BlogInstagramReelsAiGeneratorRoute
  BlogKlingImageAiRoute: typeof BlogKlingImageAiRoute
  BlogKlingVideoAiRoute: typeof BlogKlingVideoAiRoute
  BlogNanoBananaProRoute: typeof BlogNanoBananaProRoute
  BlogNanoBananaVideoGuideRoute: typeof BlogNanoBananaVideoGuideRoute
  BlogSoraAiVideoGeneratorRoute: typeof BlogSoraAiVideoGeneratorRoute
  BlogTextToVideoAiCompleteGuideRoute: typeof BlogTextToVideoAiCompleteGuideRoute
  BlogTiktokVideosWithAiRoute: typeof BlogTiktokVideosWithAiRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiTiktokCallbackRoute: typeof ApiTiktokCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-video-generator': {
      id: '/ai-video-generator'
      path: '/ai-video-generator'
      fullPath: '/ai-video-generator'
      preLoaderRoute: typeof AiVideoGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-plan': {
      id: '/choose-plan'
      path: '/choose-plan'
      fullPath: '/choose-plan'
      preLoaderRoute: typeof ChoosePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip-motion-faq': {
      id: '/clip-motion-faq'
      path: '/clip-motion-faq'
      fullPath: '/clip-motion-faq'
      preLoaderRoute: typeof ClipMotionFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion-design-ai': {
      id: '/motion-design-ai'
      path: '/motion-design-ai'
      fullPath: '/motion-design-ai'
      preLoaderRoute: typeof MotionDesignAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nanobananavideo': {
      id: '/nanobananavideo'
      path: '/nanobananavideo'
      fullPath: '/nanobananavideo'
      preLoaderRoute: typeof NanobananavideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/calendar': {
      id: '/_shell/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof ShellCalendarRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/campaigns': {
      id: '/_shell/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof ShellCampaignsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/create': {
      id: '/_shell/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof ShellCreateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/image-to-video': {
      id: '/_shell/image-to-video'
      path: '/image-to-video'
      fullPath: '/image-to-video'
      preLoaderRoute: typeof ShellImageToVideoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/images': {
      id: '/_shell/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ShellImagesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/images-legacy': {
      id: '/_shell/images-legacy'
      path: '/images-legacy'
      fullPath: '/images-legacy'
      preLoaderRoute: typeof ShellImagesLegacyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integrations': {
      id: '/_shell/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof ShellIntegrationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/posts': {
      id: '/_shell/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof ShellPostsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/product-shots': {
      id: '/_shell/product-shots'
      path: '/product-shots'
      fullPath: '/product-shots'
      preLoaderRoute: typeof ShellProductShotsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/smart-image': {
      id: '/_shell/smart-image'
      path: '/smart-image'
      fullPath: '/smart-image'
      preLoaderRoute: typeof ShellSmartImageRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/videos': {
      id: '/_shell/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof ShellVideosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/videos-legacy': {
      id: '/_shell/videos-legacy'
      path: '/videos-legacy'
      fullPath: '/videos-legacy'
      preLoaderRoute: typeof ShellVideosLegacyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/voiceover': {
      id: '/_shell/voiceover'
      path: '/voiceover'
      fullPath: '/voiceover'
      preLoaderRoute: typeof ShellVoiceoverRouteImport
      parentRoute: typeof ShellRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ai-video-ads-generator': {
      id: '/blog/ai-video-ads-generator'
      path: '/blog/ai-video-ads-generator'
      fullPath: '/blog/ai-video-ads-generator'
      preLoaderRoute: typeof BlogAiVideoAdsGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ai-video-for-ecommerce': {
      id: '/blog/ai-video-for-ecommerce'
      path: '/blog/ai-video-for-ecommerce'
      fullPath: '/blog/ai-video-for-ecommerce'
      preLoaderRoute: typeof BlogAiVideoForEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-ai-video-generators-2026': {
      id: '/blog/best-ai-video-generators-2026'
      path: '/blog/best-ai-video-generators-2026'
      fullPath: '/blog/best-ai-video-generators-2026'
      preLoaderRoute: typeof BlogBestAiVideoGenerators2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/clip-motion': {
      id: '/blog/clip-motion'
      path: '/blog/clip-motion'
      fullPath: '/blog/clip-motion'
      preLoaderRoute: typeof BlogClipMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/instagram-reels-ai-generator': {
      id: '/blog/instagram-reels-ai-generator'
      path: '/blog/instagram-reels-ai-generator'
      fullPath: '/blog/instagram-reels-ai-generator'
      preLoaderRoute: typeof BlogInstagramReelsAiGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/kling-image-ai': {
      id: '/blog/kling-image-ai'
      path: '/blog/kling-image-ai'
      fullPath: '/blog/kling-image-ai'
      preLoaderRoute: typeof BlogKlingImageAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/kling-video-ai': {
      id: '/blog/kling-video-ai'
      path: '/blog/kling-video-ai'
      fullPath: '/blog/kling-video-ai'
      preLoaderRoute: typeof BlogKlingVideoAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/nano-banana-pro': {
      id: '/blog/nano-banana-pro'
      path: '/blog/nano-banana-pro'
      fullPath: '/blog/nano-banana-pro'
      preLoaderRoute: typeof BlogNanoBananaProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/nano-banana-video-guide': {
      id: '/blog/nano-banana-video-guide'
      path: '/blog/nano-banana-video-guide'
      fullPath: '/blog/nano-banana-video-guide'
      preLoaderRoute: typeof BlogNanoBananaVideoGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/sora-ai-video-generator': {
      id: '/blog/sora-ai-video-generator'
      path: '/blog/sora-ai-video-generator'
      fullPath: '/blog/sora-ai-video-generator'
      preLoaderRoute: typeof BlogSoraAiVideoGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/text-to-video-ai-complete-guide': {
      id: '/blog/text-to-video-ai-complete-guide'
      path: '/blog/text-to-video-ai-complete-guide'
      fullPath: '/blog/text-to-video-ai-complete-guide'
      preLoaderRoute: typeof BlogTextToVideoAiCompleteGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tiktok-videos-with-ai': {
      id: '/blog/tiktok-videos-with-ai'
      path: '/blog/tiktok-videos-with-ai'
      fullPath: '/blog/tiktok-videos-with-ai'
      preLoaderRoute: typeof BlogTiktokVideosWithAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/history/': {
      id: '/_shell/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof ShellHistoryIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/history/posts': {
      id: '/_shell/history/posts'
      path: '/history/posts'
      fullPath: '/history/posts'
      preLoaderRoute: typeof ShellHistoryPostsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/': {
      id: '/_shell/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ShellProjectsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$id': {
      id: '/_shell/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ShellProjectsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/new': {
      id: '/_shell/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ShellProjectsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/tiktok/callback': {
      id: '/api/tiktok/callback'
      path: '/api/tiktok/callback'
      fullPath: '/api/tiktok/callback'
      preLoaderRoute: typeof ApiTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellCalendarRoute: typeof ShellCalendarRoute
  ShellCampaignsRoute: typeof ShellCampaignsRoute
  ShellCreateRoute: typeof ShellCreateRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellImageToVideoRoute: typeof ShellImageToVideoRoute
  ShellImagesRoute: typeof ShellImagesRoute
  ShellImagesLegacyRoute: typeof ShellImagesLegacyRoute
  ShellIntegrationsRoute: typeof ShellIntegrationsRoute
  ShellPostsRoute: typeof ShellPostsRoute
  ShellProductShotsRoute: typeof ShellProductShotsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellSmartImageRoute: typeof ShellSmartImageRoute
  ShellVideosRoute: typeof ShellVideosRoute
  ShellVideosLegacyRoute: typeof ShellVideosLegacyRoute
  ShellVoiceoverRoute: typeof ShellVoiceoverRoute
  ShellHistoryPostsRoute: typeof ShellHistoryPostsRoute
  ShellProjectsIdRoute: typeof ShellProjectsIdRoute
  ShellProjectsNewRoute: typeof ShellProjectsNewRoute
  ShellHistoryIndexRoute: typeof ShellHistoryIndexRoute
  ShellProjectsIndexRoute: typeof ShellProjectsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCalendarRoute: ShellCalendarRoute,
  ShellCampaignsRoute: ShellCampaignsRoute,
  ShellCreateRoute: ShellCreateRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellImageToVideoRoute: ShellImageToVideoRoute,
  ShellImagesRoute: ShellImagesRoute,
  ShellImagesLegacyRoute: ShellImagesLegacyRoute,
  ShellIntegrationsRoute: ShellIntegrationsRoute,
  ShellPostsRoute: ShellPostsRoute,
  ShellProductShotsRoute: ShellProductShotsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellSmartImageRoute: ShellSmartImageRoute,
  ShellVideosRoute: ShellVideosRoute,
  ShellVideosLegacyRoute: ShellVideosLegacyRoute,
  ShellVoiceoverRoute: ShellVoiceoverRoute,
  ShellHistoryPostsRoute: ShellHistoryPostsRoute,
  ShellProjectsIdRoute: ShellProjectsIdRoute,
  ShellProjectsNewRoute: ShellProjectsNewRoute,
  ShellHistoryIndexRoute: ShellHistoryIndexRoute,
  ShellProjectsIndexRoute: ShellProjectsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ShellRoute: ShellRouteWithChildren,
  AiVideoGeneratorRoute: AiVideoGeneratorRoute,
  AuthRoute: AuthRoute,
  ChoosePlanRoute: ChoosePlanRoute,
  ClipMotionFaqRoute: ClipMotionFaqRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  MotionDesignAiRoute: MotionDesignAiRoute,
  NanobananavideoRoute: NanobananavideoRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  UseCasesRoute: UseCasesRoute,
  BlogAiVideoAdsGeneratorRoute: BlogAiVideoAdsGeneratorRoute,
  BlogAiVideoForEcommerceRoute: BlogAiVideoForEcommerceRoute,
  BlogBestAiVideoGenerators2026Route: BlogBestAiVideoGenerators2026Route,
  BlogClipMotionRoute: BlogClipMotionRoute,
  BlogInstagramReelsAiGeneratorRoute: BlogInstagramReelsAiGeneratorRoute,
  BlogKlingImageAiRoute: BlogKlingImageAiRoute,
  BlogKlingVideoAiRoute: BlogKlingVideoAiRoute,
  BlogNanoBananaProRoute: BlogNanoBananaProRoute,
  BlogNanoBananaVideoGuideRoute: BlogNanoBananaVideoGuideRoute,
  BlogSoraAiVideoGeneratorRoute: BlogSoraAiVideoGeneratorRoute,
  BlogTextToVideoAiCompleteGuideRoute: BlogTextToVideoAiCompleteGuideRoute,
  BlogTiktokVideosWithAiRoute: BlogTiktokVideosWithAiRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiTiktokCallbackRoute: ApiTiktokCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
